### ISSUE TITLE
ghidra@10.0-20210621: download via aria2 failed

### ISSUE THREAD

**Issue by ycrack** [TheCjw/scoop-retools#12]
It returns 403 when I accessed.

```
$ curl -I https://ghidra-sre.org/ghidra_10.0_PUBLIC_20210621.zip
HTTP/1.1 403 Forbidden
Content-Type: application/xml
Connection: keep-alive
Date: Fri, 25 Jun 2021 01:06:25 GMT
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 f2ad9d6c3218f50a68fdbc2b2af517ab.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SFO53-C1
X-Amz-Cf-Id: uWWp4iD-3-c0rBlzhZqEidIb_3j9U8kRbGgzG1edoVOgifvfpk7RQw==
```

The URL of the file may have changed to GitHub Releases: `https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0_build/ghidra_10.0_PUBLIC_20210621.zip`

**Comment by cedws** [comment]
Yep can confirm, the new URL that checkver found doesn't work. Will change it to pull from GitHub instead.
