### ISSUE TITLE
pestudio@9.14: hash check failed

### ISSUE THREAD

**Issue by RellikJaeger** [TheCjw/scoop-retools#15]
Updating 'pestudio' (9.13 -> 9.14)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 41162e|OK  |   751KiB/s|C:/Users/Akira/scoop/cache/pestudio#9.14#https_winitor.com_tools_pestudio_current_pestudio.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of pestudio.zip ... ERROR Hash check failed!
App:         retools/pestudio
URL:         https://winitor.com/tools/pestudio/current/pestudio.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    713b0b9b6a1dae0879b5043324427c9ca42b87dfdd35597fec9433966831d687
Actual:      8706226296999bbd030e63bc44bbc70a3f07fe9df550afe129d88b4b72e7b0ca

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/TheCjw/scoop-retools/issues/new?title=pestudio%409.14%3a+hash+check+failed

**Comment by TheCjw** [comment]
Fixed #14
