### ISSUE TITLE
pestudio@9.19: hash check failed

### ISSUE THREAD

**Issue by jspaquet** [TheCjw/scoop-retools#18]
Installing 'pestudio' (9.19) [64bit]
pestudio.zip (990.9 KB) [=================================================================================================================================================] 100%
Checking hash of pestudio.zip ... ERROR Hash check failed!
App:         retools/pestudio
URL:         https://winitor.com/tools/pestudio/current/pestudio.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    f66c701f6cf8b8a0304699242b5ad892b786ff4cb2bc6725f4519a68b72a52c6
Actual:      d13e468eed3f2d0d7ddf2d27762c916cafcb971ca14d630a9ea8ce8360d7f6cb

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/TheCjw/scoop-retools/issues/new?title=pestudio%409.19%3a+hash+check+failed

**Comment by TheCjw** [comment]
Fixed at 49031aeff06ab53851b1f8c8be5128decff863f0
