### ISSUE TITLE
Include `dex2jar`

### ISSUE THREAD

**Issue by r0mflip** [TheCjw/scoop-retools#2]
I'am using apktool from this bucket and I didn't find any bucket which provides [dex2jar](https://github.com/pxb1988/dex2jar). I think it might be a tool that can be included.

But dex2jar doesn't look like it can have automatic updates(the releases are not consistent).

**Comment by TheCjw** [comment]
I wanted to add dex2jar before. But there is no stable release and too many scripts in the nightly build archive. 

But if you like it, I'll add the latest nightly build to this bucket. Many scripts may be converted to scoop shortcuts.

**Comment by r0mflip** [comment]
Yeah that would work, the nightly build is working fine. Just the thing without any update scripts should be enough.

I thought of making a PR but I am quite new to scoop.

**Comment by TheCjw** [comment]
dex2jar is added at cffa06cd7892b2031cae944dd5b2c438a2d671ae. Scripts are not fully tested, but `d2j-dex2jar` works fine.
